name: Deploy to Development

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Build
        shell: bash
        run: |
          echo "Build"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Development
        shell: bash
        run: |
          echo "Deploy to Development"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test
        shell: bash
        run: |
          echo "Test"