name: Deploy to Development

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'web/CHANGELOG.md'
      - '.github/**'
      - './*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build
        shell: bash
        run: |
          echo "Build"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Development
        shell: bash
        run: |
          echo "Deploy to Development"

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test
        shell: bash
        run: |
          echo "Test"