name: Deploy to UAT

on:
  workflow_dispatch:

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag format
        id: validate
        shell: bash
        run: |
          echo "Validating tag: ${{ github.ref_name }}"
          
          # Check if the tag starts with web-v
          if [[ ! "${{ github.ref_name }}" =~ ^web-v ]]; then
            echo "Error: Tag must start with 'web-v'"
            exit 1
          fi
          
          echo "Tag validation successful"

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        shell: bash
        run: |
          env

  deploy:
    name: 'Deploy UAT'
    runs-on: ubuntu-latest
    needs: [validate]
    environment:
      name: uat
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to UAT
        shell: bash
        run: |
          echo "deployment of tag ${{ github.ref_name }} to uat"

  playwright-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: playwright-test
        shell: bash
        run: |
          echo "playwright-test"