name: 'pr'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: 'lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: lint
        run: |
          echo "lint"