name: Release Please

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:


  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        shell: bash
        run: |
          env